spring:
  application:
    name: splitmate

  datasource:
    url: jdbc:h2:file:./data/splitmate-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:

#datasource:
#  url: jdbc:mysql://localhost:3306/splitmate_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#  username: root
#  password: root
#  driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: localhost:9992

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: splitmate-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    enabled: true
    change-log: classpath:/liquibase/master.xml

#logging:
#  level:
#    liquibase: DEBUG


